Readable cli output
strongself/fabricio pull request #39
Opened 2017-10-22 11:25 UTC by etolstoy

Added readable representations for `build`, `organization` and `app` methods.

2017-10-22 19:11 UTC, CognitiveDisson requested changes

2017-10-22 19:11 UTC, CognitiveDisson commented on lib/fabricio/models/app.rb
> +        "name: #{@name}\nid: #{@id}\nbundle_id: #{@bundle_id}\ncreated_at: #{@created_at}\nplatform: #{@platform}\nicon_url: #{@icon_url}"
я за json формат во всех вариантах. - его будет удобнее парсить в cli

2017-10-22 19:11 UTC, CognitiveDisson commented on lib/fabricio/cli.rb
> +      if options[:verbose]
в тестах видимо придется и так и так проверять. code coverage упал

2017-10-22 20:54 UTC, etolstoy commented on lib/fabricio/cli.rb
> +      if options[:verbose]
вообще не вижу тестов на cli, они были?

2017-10-22 20:55 UTC, etolstoy commented on lib/fabricio/models/app.rb
> +        "name: #{@name}\nid: #{@id}\nbundle_id: #{@bundle_id}\ncreated_at: #{@created_at}\nplatform: #{@platform}\nicon_url: #{@icon_url}"
Почему? Один вариант - не для парсинга, а для того, чтобы быстро дернуть метод и посмотреть результат. Verbose - как раз для парсинга с максимально подробной информацией.

2017-10-22 20:56 UTC, CognitiveDisson commented on lib/fabricio/cli.rb
> +      if options[:verbose]
Нет. Надо сделать. Видимо code coverage упал ниже определенного значения.

2017-10-22 20:59 UTC, CognitiveDisson commented on lib/fabricio/models/app.rb
> +        "name: #{@name}\nid: #{@id}\nbundle_id: #{@bundle_id}\ncreated_at: #{@created_at}\nplatform: #{@platform}\nicon_url: #{@icon_url}"
Мб сделать не verbose, a output type --human_readable --json

2017-10-27 14:13 UTC, etolstoy commented on lib/fabricio/models/app.rb
> +        "name: #{@name}\nid: #{@id}\nbundle_id: #{@bundle_id}\ncreated_at: #{@created_at}\nplatform: #{@platform}\nicon_url: #{@icon_url}"
Еще раз подумал – не нравится такой вариант. output_type должен менять только представление вывода, но не его содержимое. Я же хочу в кратком виде выводить только несколько параметров ответа.

2017-10-27 14:13 UTC, etolstoy commented on lib/fabricio/models/app.rb
> +        "name: #{@name}\nid: #{@id}\nbundle_id: #{@bundle_id}\ncreated_at: #{@created_at}\nplatform: #{@platform}\nicon_url: #{@icon_url}"
Вводить два параметра тоже такое себе.

2017-10-27 15:25 UTC, CognitiveDisson approved these changes

2017-10-27 15:25 UTC, merged